### ISSUE TITLE
Party is broken

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#191]

**Comment by benk0913** [comment]
Details?

**Comment by Tzook** [comment]
issues:
1. health bar doesn't show/hide/update correctly.
2. after inviting/leaving/kicking someone, char window needs to be refreshed.
3. inviting someone once and then leaving party - you can't invite someone again, it thinks you have a party.

**Comment by Tzook** [comment]
Fixed a part of number 1.

**Comment by benk0913** [comment]
@Tzook 
When client was invited to a party, he receives 2 events. one is "join party" second is "members update"
Because "members update" is sent AFTER "join party", the actor who joined the party wouldn't know it's members in the specific callback and won't be able to display their healthbars. 

On the other hand, when a different player has been joined in to your current party existing party "join party" event is called and the already existing players have to only display HIS healthbar so the healthbar is shown.

Please fix / reply if there are probz.

**Comment by Tzook** [comment]
@benk0913 I switched the order.
I still see most of the party bugs happening.

**Comment by benk0913** [comment]
Hopefully issues were fixed.
