### ISSUE TITLE
Playtest: Cockboy

### ISSUE THREAD

**Issue by Tzook** [Tzook/lel#253]
- [ ] Show Less tutorial
- [x] Npc chat (allow to skip)
- [ ] Add current Quest progress window
- [x] PA window move (?) 
- [ ] Hp above people in party instead of below
- [x] Auto open party info
- [x] Chat info still lvl 1 when char lvl up
- [ ] Show party info lvl 
- [ ] Not getting hurt when stunned
- [ ] Show Lvl/hp for mobs (lvl color red if 5+ lvl) 
- [ ] Less max font size for item descriptions
- [ ] Flashing bat cave floor
- [x] Left the party - two messages instead of one
- [x] No full inventory error
- [x] Big hat bug
- [x] Always show Npc names
- [ ] Add Spells descriptoon
- [x] Quest Fat rabbit killed info is not in one line
- [ ] Show exp gained above mob
- [ ] Hover over round values should show info
- [x] Slightly randomize spawn times
- [x] Charge bonus perk name not clear
- [ ] Aoe hits enemies behind you 
- [x] Allow Skip PA window animation
- [x] Chat frame is big - scale appropriately 
- [ ] Perk: headshot
- [ ] Jump from rope needs to be better (up)

**Comment by Tzook** [comment]
@benk0913 let me know if there's something in the list that you disagree with

**Comment by benk0913** [comment]
**Show Less tutorial** - Details?
 **Npc chat (allow to skip)** - I don't want people to auto skip.
 **Add current Quest progress window** - You mean as a small text on the top right of the screen?
 **PA window move (?)** - ?
 **Hp above people in party instead of below** - I placed it on the bottom because there's the name on the top, could put it above the name but it might be too much in one place if you include potential chat bubles. It'll also be quite high.

 **Auto open party info** - Should add and also decrease the size of the scroll, it takes too much of the screen, also X maybe hides instead of "Leaves", and an additional button for leaving?
* Also, maybe we should add shortcuts via chat, (/invite "Name" , /leave, etc...)

 **Chat info still lvl 1 when char lvl up** - A bug.
 **Show party info lvl** - Maybe would be nice, ideas for specifically where?

 **Not getting hurt when stunned** - Are you sure this happens?

 **Show Lvl/hp for mobs** (lvl color red if 5+ lvl) - maybe instead put a skull next to the mob health if it's too strong, something more subtle in any case.

 **Less max font size for item descriptions** - True, should also make sure text is not removed due to insufficient space.

 **Flashing bat cave floor** - Can't find the place.
 **Left the party - two messages instead of one** - A bug.
 **No full inventory error** - True, also causes confusion when players can't turn in quest for no clear reason... (Happened before.)

 **Big hat bug** - Fixed.
 **Always show Npc names** - Pollutes the screen, would prefer not to.

 **Add Spells descriptoon** - On hover.

 **Quest Fat rabbit killed info is not in one line** - Should it be?

 **Show exp gained above mob** - Pollutes the screen, people don't really care for that in most of the game-play time.

 **Hover over round values should show info** - Which ones?
 **Slightly randomize spawn times** -Can people really feel the robotic respawn? Not sure if necessary.

Charge bonus perk name not clear

 **Aoe hits enemies behind you** - Should be fixed
 **Allow Skip PA window animation** - Should add, upon click, should also add description / more stuff because most of the dimmed screen is unused.

 **Chat frame is big - scale appropriately** - Agree
 **Perk: headshot** - Crit Chance for ranged basically? Maybe we should add stuff which enhance headshots just like freeze... Maybe not (ranged is already OP).

 Jump from rope needs to be better (up)
